
import os
import sbms

# get env object and clone it
Import('*')

env = env.Clone()
	
sbms.Addhd_interface(env)
sbms.AddHDDM(env)
sbms.AddROOT(env)
sbms.executable(env, 'gen_ee_hb')
#sbms.executable(env)
