
import os
import sbms

# get env object and clone it
Import('*')

# Verify AMPTOOLS environment variable is set
if os.getenv('AMPTOOLS', 'nada')!='nada':

	env = env.Clone()

	sbms.AddAmpTools(env)
	sbms.AddHDDM(env)
	sbms.Addhd_interface(env)
	sbms.AddROOT(env)
	sbms.library(env)


