
import os
import sbms

# get env object and clone it
Import('*')

env = env.Clone()

AMPTOOLS_LIBS = "UTILITIES"
env.AppendUnique(LIBS = AMPTOOLS_LIBS.split())
	
sbms.Addhd_interface(env)
sbms.AddHDDM(env)
sbms.AddROOT(env)
sbms.AddUtilities(env)
sbms.executable(env, 'gen_ee')
#sbms.executable(env)
